config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end

  namespace :api do
    resources :images, only: :update
  end

  resources :images, only: :index

  resources :folders do
    resources :bookmarks
  end

  resources :notes do
    collection do
      patch :reorder
    end
  end

  resources :rooms, only: %i[index show]

  resources :messages, only: %i[create edit update] do
    resource :likes, only: %i[create destroy]
  end

  root 'home#index'
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  validates :title, presence: true
  belongs_to :folder
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit update destroy]
  before_action :set_folder
  def show; end

  def new
    @bookmark = @folder.bookmarks.build
  end

  def edit; end

  def create
    success, @bookmark = Bookmarks::CreateService.call @folder, bookmark_params

    if success
      flash.now[:success] = 'Bookmark created!'
    else
      render :new
    end
  end

  def update
    if @bookmark.update bookmark_params
      flash.now[:success] = 'Bookmark was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    flash.now[:success] = 'Bookmark was successfully destroyed.'
  end

  private

  def set_folder
    @folder = Folder.find(params[:folder_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:title)
  end
end

app/views/bookmarks/_add_bookmark.html.erb
<%= turbo_frame_tag Bookmark.new do %>
  <%= link_to 'Add Bookmark', new_folder_bookmark_path(@folder), class: 'btn btn-success' %>
<% end %>

app/views/bookmarks/_bookmark.html.erb
<%= turbo_frame_tag bookmark do %>
  <%= tag.section data: { 'bookmarks-target': 'bookmark' }, class: 'mb-4' do %>
    <%= link_to bookmark.title, folder_bookmark_path(bookmark.folder, bookmark), class: 'btn btn-warning btn-sm btn-block me-2 mb-3 ',
                data: { turbo_frame: '_top' } %>
      <div class="js-actions">
        <%= link_to :Edit, edit_folder_bookmark_path(bookmark.folder, bookmark), class: 'btn btn-primary' %>
        <%= link_to :Delete, folder_bookmark_path(bookmark.folder, bookmark), class: "btn btn-danger",
                    data: { turbo_method: :delete } %>
      </div>
  <% end %>
<% end %>

app/views/bookmarks/_form.html.erb
<%= turbo_frame_tag bookmark do %>
  <%= form_with model: [bookmark.folder, bookmark] do |f| %>
    <%= render 'shared/errors', object: bookmark %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/bookmarks/create.turbo_stream.erb
<%= turbo_stream.replace Bookmark.new, partial: 'bookmarks/add_bookmark', locals: {folder_id: @bookmark.folder.id} %>
<%= prepend_flash %>

app/views/bookmarks/created.turbo_stream.erb
<%= turbo_stream.append 'bookmarks', partial: 'bookmarks/bookmark', locals: { bookmark: bookmark } %>

app/views/bookmarks/destroy.turbo_stream.erb
<%= turbo_stream.remove @bookmark %>
<%= prepend_flash %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/new.html.erb
<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/show.html.erb
<h1><%=@bookmark.title%></h1>

<%= link_to :Back, folder_path(@bookmark.folder), class: "btn btn-secondary" %>

app/views/bookmarks/update.turbo_stream.erb
<%= turbo_stream.replace @bookmark, render(@bookmark) %>
<%= prepend_flash %>