config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end

  namespace :api do
    resources :images, only: :update
  end

  resources :images, only: :index

  resources :folders do
    resources :bookmarks
  end

  resources :notes do
    collection do
      patch :reorder
    end
  end

  resources :rooms, only: %i[index show]

  resources :messages, only: %i[create edit update] do
    resource :likes, only: %i[create destroy]
  end

  root 'home#index'
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_message, only: %i[edit update]
  def create
    success, @message = Messages::CreateService.call Current.user, message_params

    unless success
      @room = @message.room
      render 'rooms/show'
    end

    flash.now[:success] = 'Message sent!'
  end

  def edit; end

  def update
    Messages::UpdateService.call @message, update_message_params
  end

  private

  def message_params
    params.require(:message).permit(:body, :room_id)
  end

  def update_message_params
    params.require(:message).permit(:body)
  end

  def set_message
    @message = Message.find params[:id]
  end
end

app/views/messages/_form.html.erb
<%= turbo_frame_tag message do %>
  <%= form_with model: message do |f| %>
    <%= render 'shared/errors', object: message %>

    <%= f.hidden_field :room_id, value: message.room.id %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
    </div>

    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag message do %>
  <%= tag.section data: { user: message.user.id,
                          'messages-target': 'message' } do %>
    <small><%= l message.created_at, format: :long %></small><br>
    <small><%= l message.updated_at, format: :long %></small>

    <p><%= message.body %></p>
    written by <%= message.user.email %>

    <div class="js-actions d-none">
      <%= link_to 'Edit', edit_message_path(message), class: 'btn btn-secondary' %>
    </div>
  <% end %>
<% end %>

app/views/messages/_message_likes.html.erb
<%= turbo_frame_tag "message_#{message.id}_likes", data: { 'likes-target': 'widget', 'initiator': local_assigns[:initiator] } do %>
  Likes: <b><%= message.likes.count %></b>

  <div class="js_actions">
    <%= link_to :Like, message_likes_path(message), class: 'btn btn-sm btn-success d-none',
                data: { turbo_method: :post, 'likes-target': 'doLike' } %>
    <%= link_to :Unlike, message_likes_path(message), class: 'btn btn-sm btn-danger d-none',
                data: { turbo_method: :delete, 'likes-target': 'doUnlike' } %>
  </div>
<% end %>

app/views/messages/created.turbo_stream.erb
<%= turbo_stream.append "messages", partial: 'messages/message', locals: { message: message } %>

app/views/messages/edit.html.erb
<%= render 'messages/form', message: @message %>

app/views/messages/updated.turbo_stream.erb
<%= turbo_stream.replace message, partial: 'messages/message', locals: { message: message } %>