config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end

  namespace :api do
    resources :images, only: :update
  end

  resources :images, only: :index

  resources :folders do
    resources :bookmarks
  end

  resources :notes do
    collection do
      patch :reorder
    end
  end

  resources :rooms, only: %i[index show]

  resources :messages, only: %i[create edit update] do
    resource :likes, only: %i[create destroy]
  end

  root 'home#index'
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :user

  acts_as_list sequential_list: false

  validates :title, presence: true
  validates :description, presence: true
  validates :position, uniqueness: { scope: :user_id }
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[edit update]

  def index
    @notes = Note.order position: :asc
  end

  def new
    @note = Current.user.notes.build
    @note.position = Current.user.notes.count + 1
  end

  def create
    @note = Current.user.notes.build note_params
    if @note.save
      flash.now[:success] = 'Note was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @note.update note_params
      flash.now[:success] = 'Note was successfully updated.'
    else
      render :edit
    end
  end

  def reorder
    @note = Current.user.notes.find_by position: params[:old_position]
    @note.insert_at params[:new_position]

    head :ok
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :description, :position)
  end
end

app/views/notes/_add_note.html.erb
<%= turbo_frame_tag Note.new do %>
  <%= link_to 'Add Note', new_note_path, class: 'btn btn-success mb-4' %>
<% end %>

app/views/notes/_form.html.erb
<%= turbo_frame_tag note do %>
  <%= form_with model: note do |f| %>
    <%= render 'shared/errors', object: note %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :position %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.number_field :position, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/notes/_note.html.erb
<%= turbo_frame_tag note, class: 'item' do %>
  <section class="mb-4">

    <h2>
      <i class="bi bi-grip-vertical handler"></i>
      <%= note.title %>
    </h2>

    <p class="lead">
      <span class="badge bg-info" data-sortable-target="position">
        <%= note.position %>
      </span>
      <%= note.description %>
    </p>

    <%= link_to :Edit, edit_note_path(note), class: 'btn btn-primary' %>
  </section>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.replace Note.new, partial: 'add_note' %>
<%= turbo_stream.append 'notes', render(@note) %>
<%= prepend_flash %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<%= render 'add_note' %>

<%= tag.article id: 'notes', data: {controller: 'sortable'} do %>
  <%= render @notes %>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace @note, render(@note) %>
<%= prepend_flash %>