config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end

  namespace :api do
    resources :images, only: :update
  end

  resources :images, only: :index

  resources :folders do
    resources :bookmarks
  end

  resources :notes do
    collection do
      patch :reorder
    end
  end

  resources :rooms, only: %i[index show]

  resources :messages, only: %i[create edit update] do
    resource :likes, only: %i[create destroy]
  end

  root 'home#index'
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  before_action :set_folder!, only: %i[show edit update destroy]
  def index
    @folders = Folder.order created_at: :desc
  end

  def show
    @bookmarks = @folder.bookmarks.order created_at: :desc
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new folder_params
    if @folder.save
      flash.now[:success] = 'Folder created!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @folder.update folder_params
      redirect_to folders_path
    else
      render :edit
    end
  end

  def destroy
    @folder.destroy
    flash.now[:success] = 'Folder deleted!'
  end

  private

  def set_folder!
    @folder = Folder.find params[:id]
  end

  def folder_params
    params.require(:folder).permit :title, :description
  end
end

app/views/folders/_add_folder.html.erb
<%= turbo_frame_tag Folder.new do %>
  <%= link_to 'Add Folder', new_folder_path, class: 'btn btn-primary mb-4' %>
<% end %>

app/views/folders/_folder.html.erb
<%= turbo_frame_tag folder do %>
  <section class="mb-4">
    <h2><%=link_to folder.title, folder_path(folder), data: {turbo_frame: '_top'} %></h2>

    <p><%= folder.description %></p>

    <%= link_to :Edit, edit_folder_path(folder), class: 'btn btn-primary' %>
    <%= link_to :Delete, folder_path(folder), class: 'btn btn-danger',
    data: {turbo_method: :delete, turbo_confirm: 'Are u sure?'}%>
  </section>
<% end %>

app/views/folders/_form.html.erb
<%= turbo_frame_tag folder do %>
  <%= form_with model: folder do |f| %>
    <%= render 'shared/errors', object: folder %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/folders/create.turbo_stream.erb
<%= turbo_stream.replace Folder.new, partial: 'add_folder' %>
<%= turbo_stream.after Folder.new, render(@folder) %>
<%= prepend_flash %>

app/views/folders/destroy.turbo_stream.erb
<%= turbo_stream.remove @folder %>
<%= prepend_flash %>

app/views/folders/edit.html.erb
<h1>Edit Folder</h1>

<%= render 'form', folder: @folder %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<%= render 'add_folder' %>

<%= render @folders %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

app/views/folders/show.html.erb
<h1><%= @folder.title %></h1>

<p><%= @folder.description %></p>

<%= turbo_stream_from(@folder, :bookmarks) %>

<%= turbo_frame_tag 'bookmarks', data: { controller: 'bookmarks', 'bookmarks-admin-value': Current.user.admin? } do %>
  <h4>Bookmarks</h4>
  <%= render @bookmarks %>
<% end %>
<%= render 'bookmarks/add_bookmark' %>

<%= link_to :Back, folders_path, class: 'btn btn-secondary' %>